#Prgramming language used
language: python
#Language version
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter

after_success:
  - coveralls

cache: pip